
development:
  adapter: postgresql
  encoding: unicode
  database: f3_development
  pool: 5
  username: f3

test:
  adapter: postgresql
  encoding: unicode
  database: f3_test
  pool: 5
  username: f3

test:
  adapter: postgresql
  encoding: unicode
  database: f3_producation
  pool: 5
  username: f3
